
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'linerightNEGPOVleftPLUSMINUSrightUMINUSleftTIMESDIVleftPOWDIV LPAREN MINUS NUMBER PLUS POW POWER_ERROR RPAREN TIMESline : exprline : expr : NUMBERexpr : POWER_ERRORexpr : expr PLUS exprexpr : expr TIMES exprexpr : LPAREN expr RPARENexpr : expr MINUS exprexpr : expr POW exprexpr : expr POW MINUS expr %prec NEGPOVexpr : MINUS expr %prec UMINUSexpr : expr DIV expr'
    
_lr_action_items = {'$end':([0,1,2,3,4,13,14,15,16,17,19,20,21,],[-2,0,-1,-3,-4,-11,-5,-6,-8,-9,-12,-7,-10,]),'NUMBER':([0,5,6,7,8,9,10,11,18,],[3,3,3,3,3,3,3,3,3,]),'POWER_ERROR':([0,5,6,7,8,9,10,11,18,],[4,4,4,4,4,4,4,4,4,]),'LPAREN':([0,5,6,7,8,9,10,11,18,],[5,5,5,5,5,5,5,5,5,]),'MINUS':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,],[6,9,-3,-4,6,6,6,6,6,18,6,9,-11,-5,-6,-8,-9,6,-12,-7,9,]),'PLUS':([2,3,4,12,13,14,15,16,17,19,20,21,],[7,-3,-4,7,-11,-5,-6,-8,-9,-12,-7,7,]),'TIMES':([2,3,4,12,13,14,15,16,17,19,20,21,],[8,-3,-4,8,8,8,-6,8,-9,-12,-7,8,]),'POW':([2,3,4,12,13,14,15,16,17,19,20,21,],[10,-3,-4,10,10,10,10,10,-9,10,-7,10,]),'DIV':([2,3,4,12,13,14,15,16,17,19,20,21,],[11,-3,-4,11,11,11,-6,11,-9,-12,-7,11,]),'RPAREN':([3,4,12,13,14,15,16,17,19,20,21,],[-3,-4,20,-11,-5,-6,-8,-9,-12,-7,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'line':([0,],[1,]),'expr':([0,5,6,7,8,9,10,11,18,],[2,12,13,14,15,16,17,19,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> line","S'",1,None,None,None),
  ('line -> expr','line',1,'p_input_line_expr','calculator_ply.py',73),
  ('line -> <empty>','line',0,'p_input_error_nop','calculator_ply.py',77),
  ('expr -> NUMBER','expr',1,'p_expr_number','calculator_ply.py',81),
  ('expr -> POWER_ERROR','expr',1,'p_expr_power_error','calculator_ply.py',86),
  ('expr -> expr PLUS expr','expr',3,'p_expr_plus','calculator_ply.py',92),
  ('expr -> expr TIMES expr','expr',3,'p_expr_times','calculator_ply.py',98),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_group','calculator_ply.py',104),
  ('expr -> expr MINUS expr','expr',3,'p_expr_minus','calculator_ply.py',108),
  ('expr -> expr POW expr','expr',3,'p_expr_pow','calculator_ply.py',114),
  ('expr -> expr POW MINUS expr','expr',4,'p_expr_pow_neg','calculator_ply.py',120),
  ('expr -> MINUS expr','expr',2,'p_expr_uminus','calculator_ply.py',132),
  ('expr -> expr DIV expr','expr',3,'p_expr_div','calculator_ply.py',138),
]
